Encapsulamento Classe Aluno
Bruno-FMT/FullStack-Education--P1 pull request #5
Opened 2024-02-15 11:33 UTC by Bruno-FMT

2024-02-15 16:11 UTC, pamelasenai commented on objetos/Aluno.java
> +            throw new IllegalArgumentException("Idade deve estar entre 0-120");
Gostei muito desta validação.

2024-02-15 16:12 UTC, pamelasenai commented on objetos/Aluno.java
> -    public void setNome(String nome) {
Acho importante poder alterar o nome da pessoa, caso tenha sido escrito errado ou a pessoa tenha mudado seu nome, como quando casa por exemplo. Então eu manteria o setNome.

2024-02-15 16:14 UTC, pamelasenai commented on objetos/Aluno.java
> +    private ArrayList<String> cursoMatriculado = new ArrayList<>();
O professor pediu para retirar ela lista de cursos de dentro de aluno, já que teremos os alunos mariculados dentro de curso. Então acho que podemos deixar tudo isso que envolve curso dentro de curso e não em aluno.

2024-02-15 16:15 UTC, pamelasenai commented on objetos/Aluno.java
> +    public void adicionarCurso(String curso){
Assim como a lista de cursosMatriculados, acho que podemos deixar tudo que envolve curso dentro de curso e não em aluno.

2024-02-15 16:15 UTC, pamelasenai commented on objetos/Aluno.java
> +    public void removerCurso() {
Assim como a lista de cursosMatriculados, acho que podemos deixar tudo que envolve curso dentro de curso e não em aluno.

2024-02-15 16:15 UTC, pamelasenai commented on objetos/Aluno.java
> +    public void listarCursos(){
Assim como a lista de cursosMatriculados, acho que podemos deixar tudo que envolve curso dentro de curso e não em aluno.

2024-02-15 16:18 UTC, pamelasenai commented on objetos/Aluno.java
> +    public String toString(){
Perfeita inclusão. 👍 
Por mim mantemos o toString criado por você.

2024-02-15 16:19 UTC, pamelasenai commented on objetos/Aluno.java
> +        Scanner input = new Scanner(System.in);
Acho que podemos deixar a parte de solicitar nome em um método separado, como um criarUsuario ou fazerLogin e deixamos um construtor com nome e idade como obrigatórios, o que você acha?

2024-02-15 16:21 UTC, pamelasenai requested changes
Ótimo trabalho @Bruno-FMT  ,
Fiz só umas observações, veja se concorda com elas 😉

2024-02-15 19:16 UTC, Bruno-FMT commented on objetos/Aluno.java
> +    private ArrayList<String> cursoMatriculado = new ArrayList<>();
Faz mais sentido.

2024-02-15 19:20 UTC, Bruno-FMT commented on objetos/Aluno.java
> +    public void listarCursos(){
Então tanto atributos e métodos ligaos a curso implementaremos em Curso

2024-02-16 02:16 UTC, joaoxn commented on objetos/Aluno.java
> +        System.out.printf("| %13s | %6s |\n", "Nome", "Idade");
Acredito que o cabeçalho seja melhor mostrar no console quando for exibido a lista de pessoas, ao invés de mostrar para cada nova pessoa ou quando fazer o toString()

- Portanto, acho que podemos descartar a linha 36.

2024-02-16 02:19 UTC, joaoxn commented on objetos/Aluno.java
> +                "| %13s | %6d |",
A formatação retornada no toString() é maravilhosa! Porém, creio que seria melhor se a quantidade de dígitos da formatação fosse maior, já que os cadastros de uma plataforma estudantil geralmente incluem o nome completo.
- Sugestão: modificar a linha 38 de 
- "| %13s | %6d |",
- para
- "| %30s | %6d |",

2024-02-16 02:20 UTC, joaoxn commented on objetos/Aluno.java
> +import java.util.ArrayList;
A classe ArrayList e Scanner não são utilizadas no código, portanto a importação é redundante.

2024-02-16 02:22 UTC, joaoxn requested changes
Muito bom seu código e as implementações feitas, apenas fiz alguns comentários para possíveis melhorias! 👍 💯

2024-02-17 15:43 UTC, pamelasenai commented
👍

2024-02-17 15:45 UTC, merged