Herança e Interface
Bruno-FMT/FullStack-Education--P1 pull request #9
Opened 2024-02-17 17:28 UTC by ajjaum

erança, com alterações em Funcionários com a finalização de getters e setters

Interface: Funcionario e IFuncionarios, com a inclusao de promover(String nivelCargo), usando o setNivelCargo.

2024-02-17 17:35 UTC, pamelasenai commented on objetos/funcionarios/Funcionario.java
> +    public void promover(Professor professor,String nivelCargo) {
A classe funcionário se refere aos professores e diretores, então acho que podemos trocar esse parametro professor por Funcionario funcionário, o que você acha?

2024-02-17 17:37 UTC, pamelasenai commented on objetos/funcionarios/IFuncionario.java
> +    void promover(Professor professor, String nivelCargo);
A classe funcionário se refere aos professores e diretores, então acho que podemos trocar esse parametro professor por Funcionario funcionário, o que você acha?

2024-02-17 17:43 UTC, pamelasenai requested changes
Ótimo trabalho @ajjaum! 👍 
Deixei apenas umas pequenas sugestões.

2024-02-17 19:30 UTC, ajjaum commented
Então.

Eu coloquei assim, porque o único que é promovido é professor, de iniciante
para Especialista e deste para avançado. Um último degrau, a meu ver,
poderia ser de de professor avançado para diretor. Como diretor é quem
promove, é estranho ele se "autopromover" ou outro diretor promover um
diretor. O que acha?

Em sáb., 17 de fev. de 2024, 14:43, pamelasenai ***@***.***>
escreveu:

> ***@***.**** requested changes on this pull request.
>
> Ótimo trabalho @ajjaum <https://github.com/ajjaum>! 👍
> Deixei apenas umas pequenas sugestões.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Bruno-FMT/FullStack-Education--P1/pull/9#pullrequestreview-1886727228>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APK4PH652KTHTJN4BJX4Z33YUDT5HAVCNFSM6AAAAABDNOWZS6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQOBWG4ZDOMRSHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-17 21:58 UTC, pamelasenai commented
O professor tinha falado que um diretor poderia promover o outro diretor e que somente diretores promoveriam professores, também achei estranho, mas ele disse que o diretor não poderia se auto promover.

2024-02-17 22:34 UTC, ajjaum commented
Entendi!

Vou alterar então!

Obrigado!

Em sáb., 17 de fev. de 2024, 18:58, pamelasenai ***@***.***>
escreveu:

> O professor tinha falado que um diretor poderia promover o outro diretor e
> que somente diretores promoveriam professores, também achei estranho, mas
> ele disse que o diretor não poderia se auto promover.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Bruno-FMT/FullStack-Education--P1/pull/9#issuecomment-1950409078>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APK4PH4RT52CVA5NJPXDCYTYUERZPAVCNFSM6AAAAABDNOWZS6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNJQGQYDSMBXHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-18 00:46 UTC, ajjaum commented
O segundo Commit está com a alteração para Funcionario funcionario.

2024-02-18 01:20 UTC, pamelasenai approved these changes
💯 ótima implementação.

2024-02-18 03:06 UTC, merged